subscribers:

  camera_reading:
    topic: /zed/left/image_rect_color
    queue_size: 1

actions:

  camera_reading:
    name: /zed/check_for_objects

publishers:

  obstacle_boxes:
    topic: /zed/map_msg
    queue_size: 4
    frame_id: zed_obs

  object_detector:
    topic: /zed/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /zed/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /zed/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 3
  enable_console_output: true
  eval: true
  disparity_far: 10
